# Generated by Django 4.0.3 on 2022-03-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='campus',
            field=models.CharField(max_length=111, null=True),
        ),
    ]
