# Generated by Django 4.0.3 on 2022-03-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_orders_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(max_length=5000, primary_key=True, serialize=False),
        ),
    ]
