# Generated by Django 4.0.3 on 2022-03-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_orders_p_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='p_order_id',
            new_name='payment_order_id',
        ),
    ]
