# Generated by Django 4.0.3 on 2022-03-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_orders_payment_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
