# Generated by Django 4.0.3 on 2022-03-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='p_order_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='paymentorder_id',
            field=models.CharField(max_length=111, null=True),
        ),
    ]
