# Generated by Django 4.0.3 on 2022-03-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_orders_campus_remove_orders_paymentorder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='paymentorder_id',
            field=models.CharField(max_length=111, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
