# Generated by Django 4.0.3 on 2022-03-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_orders_paymentorder_id_alter_orders_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='campus',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
